apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: worldpwn/service-a:6
          ports:
            - containerPort: 8011
          readinessProbe:
            httpGet:
              path: /ping
              port: 8011
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8011
            initialDelaySeconds: 15
            periodSeconds: 20
