apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
  type: ClusterIP
