apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: worldpwn/service-b:5
          ports:
            - containerPort: 8012
          env:
            - name: SERVICE_A_URL
              valueFrom:
                configMapKeyRef:
                  name: service-b-config
                  key: SERVICE_A_URL
          readinessProbe:
            httpGet:
              path: /ping
              port: 8012
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8012
            initialDelaySeconds: 15
            periodSeconds: 20
