apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
  type: ClusterIP
