appName: service-b
replicaCount: 1

image:
  repository: worldpwn/service-b
  tag: "5"
  pullPolicy: IfNotPresent

pod:
  healthCheckPath: /ping

service:
  port: 8012

config:
  SERVICE_A_URL: "http://service-a:8011"
