name: Lint Helm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm_chart_folder: [
          applications/service-a/helm, 
          applications/service-a/helm
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.17.0' 
        id: install_helm

      - name: Install Helm Chart
        run: |
          helm lint ${{ matrix.helm_chart_folder }}
      
       