name: Multi Service Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NAMESPACE: webapp
  APP_NAME_A: service-a
  SERVICE_A_VERSION: 13
  APP_NAME_B: service-b
  SERVICE_B_VERSION: 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.17.0' 
        id: install
      - name: Install Helm Chart Deployment Service A
        run: >
          helm install ${{ env.APP_NAME_A }} applications/service-a/helm 
          --create-namespace 
          --namespace ${{ env.NAMESPACE }} 
          --set image.tag=${{ env.SERVICE_A_VERSION }}
      - name: Check Deployment Status Service A
        run: |
          kubectl rollout status deployment/${{ env.APP_NAME_A }} -n ${{ env.NAMESPACE }}
      - name: Install Helm Chart Deployment Service B
        run: >
          helm install ${{ env.APP_NAME_B }} applications/service-b/helm 
          --create-namespace 
          --namespace ${{ env.NAMESPACE }} 
          --set image.tag=${{ env.SERVICE_B_VERSION }}
          --set pod.healthCheckPath='/ping_service_a'
      - name: Check Deployment Status Service B
        run: |
          kubectl rollout status deployment/${{ env.APP_NAME_B }} -n ${{ env.NAMESPACE }}
      - name: Get Pods
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }}
