name: Build Service B Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: service-b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd applications/${{ env.APP_NAME }}/src
          docker build -t ${{ env.APP_NAME }}:${{github.run_number}} .
          docker images 

      - name: Test Web Server
        run: |
          docker run -d -p 8012:8012 ${{ env.APP_NAME }}:${{github.run_number}}
          sleep 5
          curl -s http://localhost:8012/ping
          docker ps
          docker stop $(docker ps -q)
          docker ps
