name: Publish Service A Docker Image

on:
  push:
    branches:
      - main

env:
  APP_NAME: service-a

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd applications/${{ env.APP_NAME }}/src
          docker build -t worldpwn/${{ env.APP_NAME }}:${{github.run_number}} .
          docker images 

      - name: Publish Docker Image to Docker Hub
        run: |
          docker push worldpwn/${{ env.APP_NAME }}:${{github.run_number}}
          
